In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

##Generate Data to Split

In [2]:
a= np.arange(1,101)   # same as range

In [3]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
b = np.arange(501,600)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599])

##Split the Data

In [5]:
train_test_split(a) # split train and test data arrays respectively

[array([ 65,  45,  74,  33,  84,  89,  55,  48,  90,   3,  18,  23,  51,
         60,  49,  57,  62,  78,  80,  67,  88,  31,  93,  29,  46,  75,
         95,  58,  76,  26,  22,  43,  54,  77,  10,  37,  28,   7,  39,
         13,   8,  50,  70,   4,  72,  15,  81,  69,  44,  86,  20,  99,
         16,  79,  68,  41,  94,  17,  92,   2,  56,  66,  91,  19,  38,
         87,  34, 100,  71,  53,  85,  14,  36,  21,  35]),
 array([27,  6, 24, 30, 63, 40, 64, 25, 97, 32, 59, 11, 47, 83, 98, 96, 52,
        61,  5,  9, 73, 82, 12, 42,  1])]

In [12]:
a_train, a_test= train_test_split(a, test_size =0.2) #store train and test data

In [13]:
b_train, b_test= train_test_split(b, test_size =0.2)

In [ ]:
# can also use
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size =0.2, random_state = 42)

##Explore Results

In [14]:
a_train.shape, a_test.shape

((80,), (20,))

In [15]:
a_train

array([ 14,   7,  19,  96,  33,  42,  98,  64,  55,  97,  57,  27,  32,
        31,  51,  76,  12,  46,  71,  95,  88,  47,  53,  43,   1,  72,
        25,  99,  61,  92,  86,   9,  17,  78,  20,  41,   5,  67,   3,
        45,  68,   6,  24,  11,  59,  58,  16,  66,  93,  10, 100,  34,
        87,  29,  90,  23,   8,  35,  70,  77,  44,  89,  54,  81,  91,
        15,  48,  18,  69,  30,  73,  50,  82,  94,  62,  21,  60,  40,
        79,  36])

In [19]:
a_test

array([85,  2, 52, 83, 22, 13, 56, 74, 65, 49,  4, 63, 38, 28, 80, 84, 26,
       75, 39, 37])