In [1]:
import numpy as np

##Declaring Salars, Vectors and Matrices

###Salars

In [2]:
s=5

In [3]:
s

5

In [21]:
s_array = np.array(5)
s_array

array(5)

###Vectors

In [4]:
v= np.array([5,88,23])

In [5]:
v # by default row vector

array([ 5, 88, 23])

###Matrices

In [7]:
m = np.array([[5,9,8],[10,8,99]])

In [8]:
m

array([[ 5,  9,  8],
       [10,  8, 99]])

##Data Types

In [9]:
type(s)

int

In [10]:
type(v)

numpy.ndarray

In [11]:
type(m)

numpy.ndarray

In [13]:
type(s_array)

numpy.ndarray

##Data Shapes

In [18]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [22]:
s_array.shape # scalar is 0D object

()

In [20]:
m.shape

(2, 3)

In [24]:
v.shape

(3,)

##Creating a Column Vector

In [25]:
v.reshape(1,3)

array([[ 5, 88, 23]])

In [26]:
v.reshape(3,1)

array([[ 5],
       [88],
       [23]])