In [1]:
import numpy as np

## Creating a Tensor

In [2]:
t1 = np.array([[5,8,3],[9,4,2]])
t1

array([[5, 8, 3],
       [9, 4, 2]])

In [3]:
t2 = np.array([[3,6,9],[7,5,3]])
t2

array([[3, 6, 9],
       [7, 5, 3]])

In [4]:
t = np.array([t1,t2])
t

array([[[5, 8, 3],
        [9, 4, 2]],

       [[3, 6, 9],
        [7, 5, 3]]])

##Checking its Shape

In [5]:
t.shape

(2, 2, 3)

## Manually creating a Tensor

In [6]:
t_manual = np.array([[[7,4,1],[8,5,2]],[[9,6,3],[1,5,9]]])
t_manual

array([[[7, 4, 1],
        [8, 5, 2]],

       [[9, 6, 3],
        [1, 5, 9]]])