In [1]:
import numpy as np

## Addition

In [2]:
t1 = np.array([[5,8,3],[9,4,2]])
t1

array([[5, 8, 3],
       [9, 4, 2]])

In [3]:
t2 = np.array([[3,6,9],[7,5,3]])
t2

array([[3, 6, 9],
       [7, 5, 3]])

In [7]:
t1+t2

array([[ 8, 14, 12],
       [16,  9,  5]])

##Substraction

###Example 1

In [8]:
a1 = np.array([[8,3],[9,4]])
a1

array([[8, 3],
       [9, 4]])

In [9]:
a2 = np.array([[6,9],[7,3]])
a2

array([[6, 9],
       [7, 3]])

In [10]:
a1-a2

array([[ 2, -6],
       [ 2,  1]])

###Example23

In [11]:
a3 = np.array([[8.9,53,0.88],[96.9,22,4]])
a3

array([[ 8.9 , 53.  ,  0.88],
       [96.9 , 22.  ,  4.  ]])

In [12]:
a4 = np.array([[1.8,0.3,5],[7,9,4]])
a4

array([[1.8, 0.3, 5. ],
       [7. , 9. , 4. ]])

In [13]:
a3-a4

array([[ 7.1 , 52.7 , -4.12],
       [89.9 , 13.  ,  0.  ]])