In [14]:
import numpy as np

##Transposing Metrices

In [15]:
a = np.array([[3,6,9],[7,5,3]])
a

array([[3, 6, 9],
       [7, 5, 3]])

In [17]:
a.T

array([[3, 7],
       [6, 5],
       [9, 3]])

In [18]:
b = np.array([[6,9],[7,5]])
b

array([[6, 9],
       [7, 5]])

In [19]:
b.T

array([[6, 7],
       [9, 5]])

##Transposing Scalers

In [21]:
s= np.array([5])
s

array([5])

In [22]:
s.T

array([5])

##Transposing Vectors

In [23]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [24]:
x.T

array([1, 2, 3])

In [25]:
x.shape

(3,)

In [26]:
x_re = x.reshape(1,3)
x_re

array([[1, 2, 3]])

In [27]:
x_re.T

array([[1],
       [2],
       [3]])