In [28]:
import numpy as np

##Dot Product

In [29]:
a = np.array([[8,3],[9,4]])
b = np.array([[5,8],[4,2]])


In [30]:
np.dot(a,b)

array([[52, 70],
       [61, 80]])

## Scaler * Scaler

In [31]:
np.dot(7,-1)

-7

In [32]:
np.dot(800,-56)

-44800

##Scaler * Vector

In [34]:
a

array([[8, 3],
       [9, 4]])

In [35]:
a*5

array([[40, 15],
       [45, 20]])

##Matrix *Matrix

In [40]:
a
a.shape

(2, 2)

In [39]:
x = a.T
x

array([[8, 9],
       [3, 4]])

In [38]:
a*x

array([[64, 27],
       [27, 16]])

In [44]:
#2 x 3
c = np.array( [[ 2, 5, 7 ],[ 4, 7, 9 ]] )
c

array([[2, 5, 7],
       [4, 7, 9]])

In [45]:
#3x4
d = np.array([[ 1.0, 3.5, 5.4, 7.9 ],[ 9.0, 2.5, 4.2, 3.6 ],[ 1.5, 3.2, 1.6, 6.5 ]])
d

array([[1. , 3.5, 5.4, 7.9],
       [9. , 2.5, 4.2, 3.6],
       [1.5, 3.2, 1.6, 6.5]])

In [47]:
np.dot(c,d)

array([[ 57.5,  41.9,  43. ,  79.3],
       [ 80.5,  60.3,  65.4, 115.3]])